apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: production
spec:
  ingressClassName: external-nginx
  rules:
  - host: go.drajj.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-app
            port:
              number: 80
  tls:
    - hosts:
        - go.drajj.com
      secretName: go-drajj-com
