name: CI/CD

on:
 push:
   branches:
     - main
   paths-ignore:
     - 'helm/*'
     - 'k8s/*'
     - 'README.md'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup go 1.22
      uses: actions/checkout@v2
      with:
        go-version: 1.22

    - name: Build Go artifact
      run: go build -o go-web-app

    - name: Test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repository
      uses: actions/checkout@v4
     
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        go-version: v1.56.2
    
  push:
    runs-on: ubuntu-latest

    steps:
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker logIn
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-webapp:${{ github.run_id }}
  
  update-new-in-helm-chart:
    runs-on: ubuntu-latest
    
    needs: push

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
    
    - name: update in the helm chart
      run: |
        sed -i 's/tag .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml
    
    - name: Commit and Push changes
      run: |
        git config --global user.email "ksreddy.dheeraj@gmail.com"
        git config --global user.name "Dheerajreddy9999"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
        


